version: "3.8"

volumes:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-log:
    name: foo-emqx-log

services:
  node:
    container_name: node
    image: "node:14"
    #restart: always
    working_dir: /home/node/app
    volumes:
      - ./app/:/home/node/app

    ports:
      - ${FRONT_PORT_O}:${FRONT_PORT_I}
      - ${API_PORT_O}:${API_PORT_I}
      - ${REDIRECT_PORT_O}:${REDIRECT_PORT_I}
      - ${WSS_PORT_O}:${WSS_PORT_I}
    links:
      - emqx
      - mongo

    command: sh -c "echo 'delaying 30 seconds' && sleep 30 && npm run start"
    

  mongo:
    container_name: mongo
    image: mongo:4.4
    #restart: always
    logging:
      driver: "none" 
    environment:
      TZ: "${TZ}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - ./mongodata:/data/db
    ports:
      - ${MONGO_PORT_O}:${MONGO_PORT_I}

  emqx:
    container_name: emqx
    image: emqx/emqx:4.2.3
    #restart: always
    ports:
      - ${EMQX_DASH_PORT_O}:${EMQX_DASH_PORT_I}
      - ${EMQX_TCP_PORT_O}:${EMQX_TCP_PORT_I}
      - ${EMQX_TLS_PORT_O}:${EMQX_TLS_PORT_I}
      - ${EMQX_WS_PORT_O}:${EMQX_WS_PORT_I}
      - ${EMQX_WSS_PORT_O}:${EMQX_WSS_PORT_I}
      - ${EMQX_API_PORT_O}:${EMQX_API_PORT_I}


    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-log:/opt/emqx/log
      - ./certs:/opt/emqx/etc/certs
    links:
      - mongo

    extra_hosts:
      - "localhost:192.168.0.202"

    environment:
      EMQX_NAME: omarrc-com
      EMQX_HOST: 127.0.0.1

      TZ: "${TZ}"

      # DEFAULT DASH PASS
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "${EMQX_DEFAULT_USER_PASSWORD}"

      # DEFAULT APP SECRET
      EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: "${EMQX_DEFAULT_APPLICATION_SECRET}"

      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_NOMATCH: "deny"

      # MONGO CONNECTION
      EMQX_AUTH__MONGO__TYPE: single
      EMQX_AUTH__MONGO__TOPOLOGY__POOL_SIZE: 1
      EMQX_AUTH__MONGO__TOPOLOGY__MAX_OVERFLOW: 0

      EMQX_AUTH__MONGO__SERVER: "mongo:${MONGO_PORT_I}"
      EMQX_AUTH__MONGO__POOL: 8

      EMQX_AUTH__MONGO__LOGIN: "${MONGO_USERNAME}"
      EMQX_AUTH__MONGO__PASSWORD: "${MONGO_PASSWORD}"
      EMQX_AUTH__MONGO__AUTH_SOURCE: admin

      EMQX_AUTH__MONGO__DATABASE: "ioticos_god_level"
      EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION: "emqxauthrules"

      EMQX_AUTH__MONGO__SUPER_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__SUPER_QUERY__SUPER_FIELD: "is_superuser"
      EMQX_AUTH__MONGO__SUPER_QUERY__SELECTOR: "username=%u"
      EMQX_AUTH__MONGO__SUPER_QUERY: "off"

      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: plain
      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD: "password"
      EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR: "username=%u"

      ## Enable ACL query.
      #Access control list
      EMQX_AUTH__MONGO__ACL_QUERY: "on"
      EMQX_AUTH__MONGO__ACL_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__ACL_QUERY__SELECTOR: "username=%u"

      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mongo"
      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000
      #SSL/TLS
      EMQX_LISTENER__SSL__EXTERNAL__KEYFILE: "etc/certs/emqx.key"
      EMQX_LISTENER__SSL__EXTERNAL__CERTFILE: "etc/certs/emqx.pem"
      EMQX_LISTENER__SSL__EXTERNAL__CACERTFILE: "etc/certs/ca.pem"
      #verify_peer/verify_none
      EMQX_LISTENER__SSL__EXTERNAL__VERIFY: "verify_peer"
      #listener.ssl.external.tls_versions = tlsv1.2
      EMQX_LISTENER__SSL__EXTERNAL_VERSIONS: "tlsv1.2"
      #listener.ssl.external.fail_if_no_peer_cert = false/true
      EMQX_LISTENER__SSL__EXTERNAL__FAIL_IF_NO_PEER_CERT: "false"

      #WSS
      EMQX_LISTENER__WSS__EXTERNAL__CACERTFILE: "etc/certs/ca.pem" 
      EMQX_LISTENER__WSS__EXTERNAL__CERTFILE: "etc/certs/emqx.pem"
      EMQX_LISTENER__WSS__EXTERNAL__KEYFILE: "etc/certs/emqx.key"
      
      

