version: "3.8"


services:

  node_build:
    container_name: node_build
    image: "node:14"
    working_dir: /home/node/app
    volumes:
      - ./app/:/home/node/app
      - ./certs:/home/node/app/certs

    command: sh -c "npm run build"
